version: "3"

services:
  flume:
    build:
      context: ./docker-flume
      dockerfile: Dockerfile
    # image: flume:latest
    networks:
      - data-cloud
    ports:
      - 44444:44444
    command: ["netcat-memory-logger.conf"]

  # kafka:
  #   build:
  #     context: ./docker-flume
  #     dockerfile: Dockerfile
  #     image: kafka.latest
  #   networks:
  #     - data-cloud

networks:
  data-cloud:
    driver: bridge
