version: "3"

services:
  # flume-netcat-memory-logger:
  #   build:
  #     context: ./docker-flume
  #     dockerfile: Dockerfile
  #   # image: flume:latest
  #   networks:
  #     - data-cloud
  #   ports:
  #     - 44444:44444
  #   command: ["netcat-memory-logger"]

  flume-netcat-memory-avro:
    build:
      context: ./docker-flume
      dockerfile: Dockerfile
    # image: flume:latest
    networks:
      - data-cloud
    ports:
      - 44444:44444
    command: ["netcat-memory-avro"]

  flume-avro-memory-logger:
    build:
      context: ./docker-flume
      dockerfile: Dockerfile
    # image: flume:latest
    networks:
      - data-cloud
    command: ["avro-memory-logger"]

  # kafka:
  #   build:
  #     context: ./docker-flume
  #     dockerfile: Dockerfile
  #     image: kafka.latest
  #   networks:
  #     - data-cloud

networks:
  data-cloud:
    driver: bridge
